### ISSUE TITLE
Links on Images not currently working in DA

### ISSUE THREAD

**Issue by treeves** [adobe/da-live#194] opened 2024-08-14 14:09 UTC
### Expected Behaviour
Adding a link to an image should result in an <a> tag wrapping the image.  

### Actual Behaviour
Links are being stripped and don't make it out to the preview or live hlx pages.  

### Reproduce Scenario (including but not limited to)
See https://da.live/edit#/jmphlx/jmp-da/0-sandbox/craig-test/modal-play-button-test

and https://main--jmp-da--jmphlx.hlx.live/0-sandbox/craig-test/modal-play-button-test

Link wrapped on the play button (or ANY image) should allow for a clickable link, but no sign of the link or alt shows up in the generated HTML 

#### Steps to Reproduce
See above

#### Platform and Version
Browser (any)

#### Sample Code that illustrates the problem
For https://main--jmp-da--jmphlx.hlx.page/0-sandbox/tad-test/video-test / https://da.live/edit#/jmphlx/jmp-da/0-sandbox/tad-test/video-test

The generated HTML is only: 
<html>
<body>

<p>Test</p>
--
  | <p>
  | <picture>
  | <source type="image/webp" srcset="./media_1edf6104d85203412b594b0ef56e57607f00c9358.jpeg?width=2000&#x26;format=webply&#x26;optimize=medium" media="(min-width: 600px)">
  | <source type="image/webp" srcset="./media_1edf6104d85203412b594b0ef56e57607f00c9358.jpeg?width=750&#x26;format=webply&#x26;optimize=medium">
  | <source type="image/jpeg" srcset="./media_1edf6104d85203412b594b0ef56e57607f00c9358.jpeg?width=2000&#x26;format=jpeg&#x26;optimize=medium" media="(min-width: 600px)">
  | <img loading="lazy" alt="" src="./media_1edf6104d85203412b594b0ef56e57607f00c9358.jpeg?width=750&#x26;format=jpeg&#x26;optimize=medium" width="2048" height="1536">
  | </picture>

</body>
</html>

#### Logs taken while reproducing problem

None

**Comment by bosschaert** [comment] 2024-08-16 13:29
It looks like this is caused by https://github.com/yjs/y-prosemirror/issues/165

**Comment by auniverseaway** [comment] 2024-08-20 15:28
Fixed with #199.

**Closed** 2024-10-09 19:04 UTC
